language: php

matrix:
  include:
    - php: 5.6
      dist: xenial
      env: COMPOSER_OPTIONS="--prefer-lowest"
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

install:
  - travis_retry composer update $COMPOSER_OPTIONS

script:
  - make test
