language: php

matrix:
  include:
    - php: 5.5.9
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=^3.0
    - php: 5.6
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      dist: xenial
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      dist: xenial
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      dist: xenial
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      dist: xenial
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=latest

before_install:
  # If we're requesting a specific version we can simply install it
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/config:${SYMFONY_VERSION}" --no-update ; fi
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/console:${SYMFONY_VERSION}" --no-update ; fi
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/dependency-injection:${SYMFONY_VERSION}" --no-update ; fi
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/http-foundation:${SYMFONY_VERSION}" --no-update ; fi
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/http-kernel:${SYMFONY_VERSION}" --no-update ; fi
  - if [[ $SYMFONY_VERSION != "latest" ]]; then travis_retry composer require "symfony/security-core:${SYMFONY_VERSION}" --no-update ; fi
  # If we want the latest version, install the "lastversion" script
  # see https://github.com/dvershinin/lastversion
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry pip install lastversion ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/config:$(lastversion symfony/config --pre)" --no-update ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/console:$(lastversion symfony/console --pre)" --no-update ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/dependency-injection:$(lastversion symfony/dependency-injection --pre)" --no-update ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/http-foundation:$(lastversion symfony/http-foundation --pre)" --no-update ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/http-kernel:$(lastversion symfony/http-kernel --pre)" --no-update ; fi
  - if [[ $SYMFONY_VERSION == "latest" ]]; then travis_retry composer require "symfony/security-core:$(lastversion symfony/security-core --pre)" --no-update ; fi
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - if [[ $TRAVIS_PHP_VERSION == 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-source --prefer-lowest ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-source ; fi
  # Show which versions of our direct dependencies we're using
  - composer show --direct

script:
  - make test
