language: php

matrix:
  include:
    - php: 5.5.9
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      dist: trusty
      env: SYMFONY_VERSION=^3.0
    - php: 5.6
      dist: trusty
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      dist: xenial
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      dist: xenial
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      dist: xenial
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      dist: xenial
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.2
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.3
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^3.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^4.0
    - php: 7.4
      dist: bionic
      env: SYMFONY_VERSION=^5.0
    - php: 7.4
      dist: focal
      env: SYMFONY_VERSION=latest

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - ./.ci/require-symfony.sh "$SYMFONY_VERSION"
  - if [[ $TRAVIS_PHP_VERSION == 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist ; fi
  # Show which versions of our direct dependencies we're using
  - composer show --direct

script:
  - make test
