name: Audit bugsnag-symfony dependency licenses

on: [push, pull_request]

jobs:
  license-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony-version: ['^3.4', '^4.4', '^5.0', '^6.0']

    steps:
    - uses: actions/checkout@v2

    - name: install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Fetch decisions.yml
      run: curl https://raw.githubusercontent.com/bugsnag/license-audit/master/config/decision_files/global.yml -o decisions.yml

    - name: Require Symfony
      run: ./.ci/require-symfony.sh "${{ matrix.symfony-version }}"

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest --no-interaction --no-dev

    - name: Run License Finder
      # for some reason license finder doesn't run without a login shell (-l)
      run: >
        docker run -v $PWD:/scan licensefinder/license_finder /bin/bash -lc "
          cd /scan &&
          license_finder --decisions-file decisions.yml --composer-check-require-only=true --enabled-package-managers=composer
        "
