name: Maze Runner tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0']
        symfony-version: [4, 5, 6]
        include:
          - php-version: '7.2'
            symfony-version: 2
          - php-version: '8.3'
            symfony-version: 7

    steps:
    - uses: actions/checkout@v2

    - name: Install libcurl4-openssl-dev and net-tools
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install net-tools

    - name: install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - run: bundle exec maze-runner --no-source
      env:
        PHP_VERSION: ${{ matrix.php-version }}
        SYMFONY_VERSION: ${{ matrix.symfony-version }}
        COMPOSER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
